name: Fix docs linting errors
on: workflow_dispatch
jobs:
  docs-lint-fix:
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout
          uses: actions/checkout@v2
      -   name: Lint & fix Markdown docs
          run: yarn && yarn docs:lint:fix
      -   name: Push changes back to repository
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Lintingâ„¢
